export const texts={
    USERS_LISTS:'Users LIst',
    NIFTY_50:'NIFTY 50',
    17755:'17755.00',
    160:'+160.65(+0.91%)',
    SENSEX:'SENSEX',
    60397:'60397.62',
    588:'588.65(+0.98%)',
    NOR:'NOR',
    EXTRA:'Extra',
    ADD:'Add',
    NIFTY:'Nifty',
    OTHER:'OTHER',
    SIGNUP_INFO:'Signup with your mobile and start 15 days(s) free trial now',
    SIGNUP:'Sign Up',
    LOGIN:'Login',
    FORGOT_PASS:'Forgot Password',
    REGISTER:'Register',
    NOT_REGISTERED:"Haven't registered yet?Click here to",
    EXCHANGES:'Availble Exchanges',
    TIMINGS:'Exchange Timings',
    ABOUT_US:'About Us',
    MEMBERSHIP:'Membership Details',
    SELECT_WATCHLIST:'Select Watchlist',
    CREATE_WATCHLIST:'Create Watchlist',
    TRADE:'Trade',
    DONT_MISS:'Dont Miss'
}